// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSdzKZZsaP9lJi5G9FBi66zO7oEZlWJik',
    appId: '1:364817211720:web:89b80a42221769e195137d',
    messagingSenderId: '364817211720',
    projectId: 'todo-list-20e4c',
    authDomain: 'todo-list-20e4c.firebaseapp.com',
    storageBucket: 'todo-list-20e4c.appspot.com',
    measurementId: 'G-PJDGBM1MWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYQFeP9nGcqUJOjfrrK1p--ZzfbUVTZY',
    appId: '1:364817211720:android:a57cd24229ec6cb295137d',
    messagingSenderId: '364817211720',
    projectId: 'todo-list-20e4c',
    storageBucket: 'todo-list-20e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8r11by5ZxTXDNBL0_pGLRGA-bSNnUTIc',
    appId: '1:364817211720:ios:0be8e59ca71ccae895137d',
    messagingSenderId: '364817211720',
    projectId: 'todo-list-20e4c',
    storageBucket: 'todo-list-20e4c.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
